# Generated by Django 5.1.6 on 2025-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id_pokemon', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pokemon', models.CharField(default='', max_length=20)),
                ('tipo_pokemon', models.CharField(default='', max_length=8)),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bioma', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
