# Generated by Django 5.1.6 on 2025-02-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id_treinador', models.AutoField(primary_key=True, serialize=False)),
                ('nome_treinador', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
    ]
