# Generated by Django 5.1.6 on 2025-02-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_treinador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id_ataque', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ataque', models.CharField(max_length=50)),
                ('tipo_ataque', models.CharField(max_length=20)),
                ('dano', models.IntegerField(default=0)),
                ('precisao', models.IntegerField(default=0)),
                ('pp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id_regiao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_regiao', models.CharField(max_length=50)),
            ],
        ),
    ]
