# Generated by Django 5.1.6 on 2025-02-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ataque_regiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon_Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ataque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataque_pokemons', to='api.ataque')),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_ataques', to='api.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon_Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_regioes', to='api.pokemon')),
                ('id_regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiao_pokemons', to='api.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon_Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_treinadores', to='api.pokemon')),
                ('id_treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinador_pokemons', to='api.treinador')),
            ],
        ),
    ]
