# Configuração do Banco

spring.application.name=pokedex
spring.datasource.url=jdbc:postgresql://localhost:5433/pokedex
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=validate  
spring.jpa.show-sql=true  
spring.jpa.properties.hibernate.format_sql=true 
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=false
  